grafana:
  adminPassword: admin
  service:
    type: ClusterIP
  ingress:
    enabled: false
  image:
    repository: docker.io/grafana/grafana
    tag: "10.2.0"
    registry: ""  # Will be set via --set in workflow
  sidecar:
    dashboards:
      image:
        repository: quay.io/kiwigrid/k8s-sidecar
        tag: "2.1.2"  # Helm Chart default version
        registry: ""  # Will be set via --set in workflow
    datasources:
      image:
        repository: quay.io/kiwigrid/k8s-sidecar
        tag: "2.1.2"  # Helm Chart default version
        registry: ""  # Will be set via --set in workflow

prometheus:
  prometheusSpec:
    retention: 7d
    image:
      repository: quay.io/prometheus/prometheus
      tag: "v2.48.0"
      registry: ""  # Will be set via --set in workflow

alertmanager:
  enabled: true
  image:
    repository: quay.io/prometheus/alertmanager
    tag: "v0.29.0"  # Helm Chart default version
    registry: ""  # Will be set via --set in workflow

prometheusOperator:
  image:
    repository: quay.io/prometheus-operator/prometheus-operator
    tag: "v0.86.2"
    registry: ""  # Will be set via --set in workflow
  prometheusConfigReloader:
    image:
      repository: quay.io/prometheus-operator/prometheus-config-reloader
      tag: "v0.86.2"
      registry: ""  # Will be set via --set in workflow
  configmapReload:
    prometheus:
      image:
        repository: quay.io/prometheus-operator/prometheus-config-reloader
        tag: "v0.86.2"
        registry: ""  # Will be set via --set in workflow
    alertmanager:
      image:
        repository: quay.io/prometheus-operator/prometheus-config-reloader
        tag: "v0.86.2"
        registry: ""  # Will be set via --set in workflow
  admissionWebhooks:
    patch:
      image:
        repository: docker.io/jettech/kube-webhook-certgen
        tag: "v1.5.1"
        registry: ""  # Will be set via --set in workflow

"prometheus-node-exporter":
  image:
    repository: quay.io/prometheus/node-exporter
    tag: "v1.10.2"
    registry: ""  # Will be set via --set in workflow

kube-state-metrics:
  image:
    repository: registry.k8s.io/kube-state-metrics/kube-state-metrics
    tag: "v2.10.1"
    registry: ""  # Will be set via --set in workflow


