apiVersion: v1
kind: ServiceAccount
metadata:
  name: cicd-deploy
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cicd-deploy-role
rules:
  # Namespaces verwalten
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["create", "get", "list", "watch"]
  # Deployments, Services, ConfigMaps, Secrets
  - apiGroups: ["apps"]
    resources: ["deployments", "daemonsets", "statefulsets"]
    verbs: ["create", "update", "patch", "delete", "get", "list", "watch"]
  - apiGroups: [""]
    resources: ["services", "configmaps", "secrets", "pods", "endpoints"]
    verbs: ["create", "update", "patch", "delete", "get", "list", "watch"]
  # ServiceAccounts
  - apiGroups: [""]
    resources: ["serviceaccounts"]
    verbs: ["create", "update", "patch", "get", "list", "watch", "impersonate"]
  # Helm/Kubectl managed RBAC objects
  - apiGroups: ["rbac.authorization.k8s.io"]
    resources: ["roles", "rolebindings", "clusterroles", "clusterrolebindings"]
    verbs: ["create", "get", "list", "watch", "update", "patch", "delete"]
  # Für Verifikation und Metrics Server
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list", "watch"]
  # Nodes metrics für Metrics Server
  - apiGroups: [""]
    resources: ["nodes/metrics"]
    verbs: ["get"]
  # Storage class adjustments (e.g. local-path default)
  - apiGroups: ["storage.k8s.io"]
    resources: ["storageclasses"]
    verbs: ["create", "get", "list", "watch", "update", "patch", "delete"]
  # Für Metrics Server - metrics.k8s.io API
  - apiGroups: ["metrics.k8s.io"]
    resources: ["*"]
    verbs: ["get", "list", "watch"]
  # Authentication/Authorization für system:auth-delegator (Metrics Server)
  - apiGroups: ["authentication.k8s.io"]
    resources: ["tokenreviews"]
    verbs: ["create"]
  - apiGroups: ["authorization.k8s.io"]
    resources: ["subjectaccessreviews"]
    verbs: ["create"]
  # APIServices für Metrics Server API registration
  - apiGroups: ["apiregistration.k8s.io"]
    resources: ["apiservices"]
    verbs: ["create", "get", "list", "watch", "update", "patch", "delete"]
  # Networking: Ingresses für Database-Management
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingresses", "ingressclasses"]
    verbs: ["create", "get", "list", "watch", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cicd-deploy-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cicd-deploy-role
subjects:
  - kind: ServiceAccount
    name: cicd-deploy
    namespace: kube-system

