apiVersion: v1
kind: ServiceAccount
metadata:
  name: cicd-deploy
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cicd-deploy-role
rules:
  # Namespaces verwalten
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["create", "get", "list", "watch"]
  # Deployments, Services, ConfigMaps, Secrets
  - apiGroups: ["apps"]
    resources: ["deployments", "daemonsets", "statefulsets"]
    verbs: ["create", "update", "patch", "delete", "get", "list", "watch"]
  - apiGroups: [""]
    resources: ["services", "configmaps", "secrets", "pods", "endpoints"]
    verbs: ["create", "update", "patch", "delete", "get", "list", "watch"]
  # ServiceAccounts
  - apiGroups: [""]
    resources: ["serviceaccounts"]
    verbs: ["create", "update", "patch", "get", "list", "watch"]
  # Helm/Kubectl managed RBAC objects
  - apiGroups: ["rbac.authorization.k8s.io"]
    resources: ["roles", "rolebindings", "clusterroles", "clusterrolebindings"]
    verbs: ["create", "get", "list", "watch", "update", "patch", "delete"]
  # Für Verifikation
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list"]
  # Storage class adjustments (e.g. local-path default)
  - apiGroups: ["storage.k8s.io"]
    resources: ["storageclasses"]
    verbs: ["create", "get", "list", "watch", "update", "patch", "delete"]
  # Für Metrics Server
  - apiGroups: ["metrics.k8s.io"]
    resources: ["*"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cicd-deploy-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cicd-deploy-role
subjects:
  - kind: ServiceAccount
    name: cicd-deploy
    namespace: kube-system

