apiVersion: v1
kind: ServiceAccount
metadata:
  name: cicd-deploy
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cicd-deploy-role
rules:
  # Namespaces verwalten
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["create", "get", "list", "watch"]
  # Deployments und DaemonSets
  - apiGroups: ["apps"]
    resources: ["deployments", "daemonsets"]
    verbs: ["create", "update", "patch", "delete", "get", "list", "watch"]
  # StatefulSets mit allen Verben für Prometheus Operator
  - apiGroups: ["apps"]
    resources: ["statefulsets"]
    verbs: ["*"]
  - apiGroups: [""]
    resources: ["services", "pods", "pods/log", "endpoints", "events"]
    verbs: ["create", "update", "patch", "delete", "get", "list", "watch"]
  # ConfigMaps und Secrets mit allen Verben für Prometheus Operator
  - apiGroups: [""]
    resources: ["configmaps", "secrets"]
    verbs: ["*"]
  # Services finalizers für Prometheus Operator
  - apiGroups: [""]
    resources: ["services/finalizers"]
    verbs: ["get", "create", "update", "delete"]
  # ServiceAccounts
  - apiGroups: [""]
    resources: ["serviceaccounts"]
    verbs: ["create", "update", "patch", "delete", "get", "list", "watch", "impersonate"]
  # Helm/Kubectl managed RBAC objects
  - apiGroups: ["rbac.authorization.k8s.io"]
    resources: ["roles", "rolebindings", "clusterroles", "clusterrolebindings"]
    verbs: ["create", "get", "list", "watch", "update", "patch", "delete"]
  # Jobs für Helm Hooks (z.B. NGINX Ingress admission jobs)
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["create", "get", "list", "watch", "update", "patch", "delete"]
  # Für Verifikation und Metrics Server
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list", "watch"]
  # Nodes metrics für Metrics Server und Prometheus
  - apiGroups: [""]
    resources: ["nodes/metrics"]
    verbs: ["get", "list", "watch"]
  # Storage class adjustments (e.g. local-path default)
  - apiGroups: ["storage.k8s.io"]
    resources: ["storageclasses"]
    verbs: ["create", "get", "list", "watch", "update", "patch", "delete"]
  # PersistentVolumes und PersistentVolumeClaims für Local Path Provisioner RBAC
  - apiGroups: [""]
    resources: ["persistentvolumes", "persistentvolumeclaims"]
    verbs: ["create", "get", "list", "watch", "update", "patch", "delete"]
  # Für Metrics Server - metrics.k8s.io API
  - apiGroups: ["metrics.k8s.io"]
    resources: ["*"]
    verbs: ["get", "list", "watch"]
  # Authentication/Authorization für system:auth-delegator (Metrics Server)
  - apiGroups: ["authentication.k8s.io"]
    resources: ["tokenreviews"]
    verbs: ["create"]
  - apiGroups: ["authorization.k8s.io"]
    resources: ["subjectaccessreviews"]
    verbs: ["create"]
  # APIServices für Metrics Server API registration
  - apiGroups: ["apiregistration.k8s.io"]
    resources: ["apiservices"]
    verbs: ["create", "get", "list", "watch", "update", "patch", "delete"]
  # Networking: Ingresses für Database-Management
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingresses", "ingressclasses"]
    verbs: ["create", "get", "list", "watch", "update", "patch", "delete"]
  # Admission Webhooks für NGINX Ingress Controller
  - apiGroups: ["admissionregistration.k8s.io"]
    resources: ["validatingwebhookconfigurations", "mutatingwebhookconfigurations"]
    verbs: ["create", "get", "list", "watch", "update", "patch", "delete"]
  # Events für NGINX Ingress Controller und Prometheus Operator
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create", "patch"]
  # Events API group für Prometheus Operator
  - apiGroups: ["events.k8s.io"]
    resources: ["events"]
    verbs: ["patch", "create"]
  # Leases für Leader Election (NGINX Ingress Controller)
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["create", "get", "update", "list", "watch"]
  # EndpointSlices für Service Discovery (NGINX Ingress Controller und Prometheus Operator)
  - apiGroups: ["discovery.k8s.io"]
    resources: ["endpointslices"]
    verbs: ["create", "update", "delete", "get", "list", "watch"]
  # Ingress Status Updates für NGINX Ingress Controller
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingresses/status"]
    verbs: ["update"]
  # CustomResourceDefinitions für Helm Charts (z.B. Prometheus Stack CRDs)
  - apiGroups: ["apiextensions.k8s.io"]
    resources: ["customresourcedefinitions"]
    verbs: ["create", "get", "list", "watch", "update", "patch", "delete"]
  # Monitoring CRDs für Prometheus Stack (Alertmanager, Prometheus, ServiceMonitor, etc.)
  - apiGroups: ["monitoring.coreos.com"]
    resources: ["alertmanagers", "prometheuses", "servicemonitors", "podmonitors", "prometheusrules", "alertmanagerconfigs", "probes", "scrapeconfigs", "thanosrulers", "prometheusagents"]
    verbs: ["*"]
  # Monitoring CRDs Status und Finalizers Subresources für Prometheus Operator
  - apiGroups: ["monitoring.coreos.com"]
    resources: ["alertmanagers/status", "alertmanagers/finalizers", "prometheuses/status", "prometheuses/finalizers", "servicemonitors/status", "podmonitors/status", "probes/status", "scrapeconfigs/status", "thanosrulers/status", "thanosrulers/finalizers", "prometheusagents/status", "prometheusagents/finalizers"]
    verbs: ["*"]
  # Zusätzliche Permissions für kube-state-metrics ClusterRole
  # LimitRanges und ResourceQuotas
  - apiGroups: [""]
    resources: ["limitranges", "resourcequotas"]
    verbs: ["list", "watch"]
  # ReplicationControllers
  - apiGroups: [""]
    resources: ["replicationcontrollers"]
    verbs: ["list", "watch"]
  # ReplicaSets (apps API group)
  - apiGroups: ["apps"]
    resources: ["replicasets"]
    verbs: ["list", "watch"]
  # HorizontalPodAutoscalers
  - apiGroups: ["autoscaling"]
    resources: ["horizontalpodautoscalers"]
    verbs: ["list", "watch"]
  # CronJobs (batch API group)
  - apiGroups: ["batch"]
    resources: ["cronjobs"]
    verbs: ["list", "watch"]
  # CertificateSigningRequests
  - apiGroups: ["certificates.k8s.io"]
    resources: ["certificatesigningrequests"]
    verbs: ["list", "watch"]
  # NetworkPolicies
  - apiGroups: ["networking.k8s.io"]
    resources: ["networkpolicies"]
    verbs: ["list", "watch"]
  # PodDisruptionBudgets
  - apiGroups: ["policy"]
    resources: ["poddisruptionbudgets"]
    verbs: ["list", "watch"]
  # VolumeAttachments
  - apiGroups: ["storage.k8s.io"]
    resources: ["volumeattachments"]
    verbs: ["list", "watch"]
  # NonResourceURLs für Prometheus (nodes metrics endpoints)
  - nonResourceURLs: ["/metrics", "/metrics/cadvisor"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cicd-deploy-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cicd-deploy-role
subjects:
  - kind: ServiceAccount
    name: cicd-deploy
    namespace: kube-system

